#!/bin/bash
# Status Monitor - Caddy Setup Script
# This script helps configure the application for deployment with Caddy and Cloudflare

set -e

echo "========================================="
echo "Status Monitor - Caddy Setup"
echo "========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colored output
print_success() { echo -e "${GREEN}✓ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠ $1${NC}"; }
print_error() { echo -e "${RED}✗ $1${NC}"; }

# Check if docker is installed
if ! command -v docker &> /dev/null; then
    print_error "Docker is not installed. Please install Docker first."
    exit 1
fi
print_success "Docker is installed"

# Check if docker-compose is installed
if ! command -v docker-compose &> /dev/null; then
    print_error "Docker Compose is not installed. Please install Docker Compose first."
    exit 1
fi
print_success "Docker Compose is installed"

echo ""
echo "This script will help you configure Status Monitor with Caddy and Cloudflare."
echo ""

# Ask for domain configuration
echo "=== Domain Configuration ==="
read -p "Enter your primary domain (e.g., status.example.com): " DOMAIN
read -p "Do you want to use separate subdomains for API? (y/n): " USE_SUBDOMAIN

if [ "$USE_SUBDOMAIN" = "y" ] || [ "$USE_SUBDOMAIN" = "Y" ]; then
    read -p "Enter your API subdomain (e.g., api.status.example.com): " API_DOMAIN
    API_URL="https://${API_DOMAIN}"
    WS_URL="wss://${API_DOMAIN}/ws/live"
    SETUP_TYPE="subdomain"
else
    API_URL="https://${DOMAIN}/api"
    WS_URL="wss://${DOMAIN}/ws/live"
    SETUP_TYPE="path"
fi

echo ""
print_success "Domain configuration:"
echo "  Primary domain: ${DOMAIN}"
if [ "$SETUP_TYPE" = "subdomain" ]; then
    echo "  API domain: ${API_DOMAIN}"
else
    echo "  API path: ${DOMAIN}/api"
fi
echo "  API URL: ${API_URL}"
echo "  WebSocket URL: ${WS_URL}"
echo ""

# Create .env file
echo "=== Creating .env file ==="
cat > .env << EOF
# Generated by setup-caddy.sh

DOMAIN=${DOMAIN}
API_DOMAIN=${API_DOMAIN:-${DOMAIN}}

NEXT_PUBLIC_API_URL=${API_URL}
NEXT_PUBLIC_WS_URL=${WS_URL}

DATABASE_URL=sqlite:/app/data/monitor.db
RUST_LOG=server=info,tower_http=info

REGISTRY=ghcr.io
IMAGE_OWNER=nyovelt
IMAGE_TAG=latest
EOF

print_success ".env file created"

# Update Caddyfile
echo ""
echo "=== Configuring Caddyfile ==="

if [ "$SETUP_TYPE" = "subdomain" ]; then
    # Use subdomain configuration
    cat > Caddyfile << EOF
# Caddyfile for Status Monitor - Subdomain Configuration
# Generated by setup-caddy.sh

# Frontend - Web UI
${DOMAIN} {
    reverse_proxy web:3000
    encode gzip zstd

    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Frame-Options "SAMEORIGIN"
        X-Content-Type-Options "nosniff"
        X-XSS-Protection "1; mode=block"
        -Server
    }

    log {
        output file /var/log/caddy/status-access.log
    }
}

# Backend API
${API_DOMAIN} {
    reverse_proxy server:8080

    @websockets {
        header Connection *Upgrade*
        header Upgrade websocket
    }
    reverse_proxy @websockets server:8080

    encode gzip zstd

    header {
        -Server
        X-Content-Type-Options "nosniff"
    }

    log {
        output file /var/log/caddy/api-access.log
    }
}
EOF
else
    # Use path-based configuration
    cat > Caddyfile << EOF
# Caddyfile for Status Monitor - Path-based Configuration
# Generated by setup-caddy.sh

${DOMAIN} {
    # Frontend - serve from root
    reverse_proxy web:3000

    # API endpoints - proxy /api/* to backend
    handle_path /api/* {
        reverse_proxy server:8080
    }

    # WebSocket endpoint for live updates
    @websockets {
        path /ws/*
        header Connection *Upgrade*
        header Upgrade websocket
    }
    reverse_proxy @websockets server:8080

    encode gzip zstd

    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Frame-Options "SAMEORIGIN"
        X-Content-Type-Options "nosniff"
        X-XSS-Protection "1; mode=block"
        -Server
    }

    log {
        output file /var/log/caddy/status-access.log
    }
}
EOF
fi

print_success "Caddyfile configured"

# Create data directory
echo ""
echo "=== Creating data directory ==="
mkdir -p data
chmod 755 data
print_success "Data directory created"

echo ""
echo "========================================="
echo "Configuration Complete!"
echo "========================================="
echo ""
print_warning "Next Steps:"
echo ""
echo "1. Configure Cloudflare DNS:"
if [ "$SETUP_TYPE" = "subdomain" ]; then
    echo "   - Create A record: ${DOMAIN} → Your Server IP"
    echo "   - Create A record: ${API_DOMAIN} → Your Server IP"
else
    echo "   - Create A record: ${DOMAIN} → Your Server IP"
fi
echo ""
echo "2. Set Cloudflare SSL/TLS mode to 'Full' or 'Full (strict)'"
echo ""
echo "3. Deploy the application:"
echo "   docker-compose -f docker-compose.caddy.yml up -d"
echo ""
echo "4. Check logs:"
echo "   docker-compose -f docker-compose.caddy.yml logs -f"
echo ""
echo "5. Access your application:"
echo "   https://${DOMAIN}"
echo ""
print_success "Setup complete! Good luck! 🚀"
